opensearch-project/ansible-playbook

- roles/centos7/dashboards/tasks/main.yml
- roles/centos7/dashboards/tasks/tune.yml
- roles/centos7/dashboards/templates/dashboards.service
- roles/centos7/opensearch/tasks/main.yml
- roles/centos7/opensearch/tasks/tune.yml
- roles/centos7/opensearch/templates/opensearch.service
- roles/centos7/opensearch/templates/opensearch.yml
Add the recommended settings from Opensearch.
Refer: https://opensearch.org/docs/latest/opensearch/install/important-settings/
#9
> [issue - 9] add important settings

- roles/centos7/opensearch/tasks/security.yml
Fix #24 
`.tar.gz` works fine for both Mac OS and linux PCs.
> Fix unarchive issues in linux clients

- inventories/opensearch/group_vars/all/all.yml
- roles/linux/dashboards/tasks/dashboards.yml
- roles/linux/dashboards/tasks/main.yml
- roles/linux/dashboards/templates/dashboards.service
- roles/linux/opensearch/templates/opensearch.service
Fix Issue: #30 
Only `user` variable is enough, adding `group` variable will create issues.
Linux creates both user and group during an user creation, and we can use the same user and group for running an application. If we provide another separate variable for `group` then someone may use two different values for `user` and `group` that requires another group creation and further group management which is unnecessary and tedious process.
> [Fix issue-30] Add opensearch/dashboards specific user variable to define user and group on creation

- inventories/opensearch/group_vars/all/all.yml
Bump opensearch version to 1.2.4 in ansible playbook
[List any issues this PR will resolve]
> Bump opensearch version to 1.2.4 in ansible playbook

- inventories/opensearch/group_vars/all/all.yml
- roles/linux/opensearch/tasks/opensearch.yml
Issue #39 
Instead of copying whole file(which doing overwrite the complete file), validating the content and copying only the content.
@peterzhuamazon  Tested only with `single-node`. Cluster is fine even after 2 times re-run.
> issue #39 workaround for opensearch config override

- README.md
- inventories/opensearch/group_vars/all/all.yml
1.x only have 1.x opensearch/dashboards apps
Part of opensearch-project/opensearch-build#2086
> 1.x only have 1.x opensearch/dashboards apps

- roles/linux/dashboards/tasks/dashboards.yml
Signed-off-by: Sergey Shubin <serg@ssid.name>
After apply role "dashboards", service dashboards does not starting with error message "opensearch-dashboards[219171]: FATAL Error: Unable to write OpenSearch Dashboards UUID file, please check the uuid.server configuration value in opensearch_dashboards.yml and ensure OpenSearch Dashboards has sufficient permissions to read / write to this file. Error was: EACCES"
> Troubleshooting error launching dashboards after installation

- .github/CODEOWNERS
[Backport 1.x] Add saravanan30erd as the default reviewer of ansible repo
> [Backport 1.x] Add saravanan30erd as the default reviewer of ansible repo

- README.md
- files/internal_users.yml
- files/roles.yml
- files/roles_mapping.yml
- files/tenants.yml
- inventories/opensearch/group_vars/all/all.yml
- roles/linux/dashboards/defaults/main.yml
- roles/linux/dashboards/tasks/dashboards.yml
- roles/linux/dashboards/templates/opensearch_dashboards.yml
- roles/linux/opensearch/defaults/main.yml
- roles/linux/opensearch/tasks/opensearch.yml
- roles/linux/opensearch/tasks/security.yml
- roles/linux/opensearch/templates/security_plugin_conf.yml
- roles/linux/opensearch/templates/tlsconfig.yml
1. Added the ability to log in via OpenID
2. Added the ability to install custom configuration files for the cluster
3. Added the ability to reconfigure the cluster (in particular, update certificates) when expanding it
4. Added the ability not to change certificates if the cluster composition has not changed, but only the settings have changed.
https://github.com/opensearch-project/ansible-playbook/issues/61
> OIDC auth, custom configs

- roles/linux/opensearch/tasks/security.yml
Signed-off-by: Rodolfo Camara Villordo <rodolfovillordo@gmail.com>
Fix missing plugin configuration directory
https://github.com/opensearch-project/ansible-playbook/issues/80
> [1.x] Fix nonexistent "os_sec_plugin_conf_path" directory error.

- roles/linux/opensearch/defaults/main.yml
- roles/linux/opensearch/tasks/security.yml
Fix nonexistent os_sec_plugin_conf_path directory error.
#80
> Fix nonexistent os_sec_plugin_conf_path directory error

- roles/linux/opensearch/tasks/security.yml
Signed-off-by: Rodolfo Camara Villordo <rodolfovillordo@gmail.com>
removes unnecessary elevation of privileges
resolve #82 
> become: false on "Check that the files/internal_users.yml exists"

- roles/linux/opensearch/tasks/security.yml
Signed-off-by: Rodolfo Camara Villordo <rodolfovillordo@gmail.com>
Chenge condition to execute the securityadmin.sh script with the parameter `-cd` only when copy_custom_security_configs is true. Also add a task to execute securityadmin.sh with parameter `-f` when copy_custom_security_configs is set to false.
fix #83 
> Fix securityadmin.sh when copy_custom_security_configs is False

- roles/linux/opensearch/tasks/security.yml
[Backport 1.x] Fix securityadmin.sh when copy_custom_security_configs is False
#83
> [Backport 1.x] Fix securityadmin.sh when copy_custom_security_configs is False

- roles/linux/opensearch/tasks/security.yml
[Backport 1.x] become: false on "Check that the files/internal_users.yml exists"
#82
> [Backport 1.x] become: false on "Check that the files/internal_users.yml exists"

- inventories/opensearch/group_vars/all/all.yml
bump opensearch and opensearch-dashboards version to 1.3.9
post task of release 1.3.9 at https://github.com/opensearch-project/opensearch-build/issues/3195
> bump opensearch and opensearch-dashboards version to 1.3.9

- .github/workflows/github-merit-badger.yml
Adding the POC of [github-merit-badger](https://github.com/aws-github-ops/github-merit-badger)
The labels as part of badges are auto created.
Sample tested PR: https://github.com/prudhvigodithi/opensearch-build/pull/51
This github-merit-badger would give better insights to repo maintainers and would enhance the open source community experience.
> Add github-merit-badger.yml

- roles/linux/opensearch/tasks/security.yml
instead of waiting hard-coded 10 seconds, better wait for the API port of opensearch to become available.
This is done in the same way in `roles/linux/opensearch/tasks/main.yml`, from where the replacing code was taken.
> wait for port to be open instead of hard-coded 10 seconds

- roles/linux/opensearch/tasks/security.yml
[Backport 1.x] Wait for port to be open instead of hard-coded 10 seconds
https://github.com/opensearch-project/ansible-playbook/pull/123
> [Backport 1.x] Wait for port to be open instead of hard-coded 10 seconds

- README.md
Update documentation to add missing `logstash` environment password.
https://github.com/opensearch-project/ansible-playbook/issues/134
> Add missing logstash environment on documentation

- roles/linux/opensearch/tasks/security.yml
Fix implementation as suggested in issue:
Copy security config when: auth_type == 'oidc' or copy_custom_security_configs
#116
> Copy custom security config when: auth_type == 'oidc' or copy_custom_security_configs

- README.md
> Updates README to reflect strong password requirements for admin user

- inventories/opensearch/group_vars/all/all.yml
Update 2.x ansible playbook to use 2.15.0 release
https://github.com/opensearch-project/opensearch-build/issues/4681
> Update 2.x ansible playbook to use 2.15.0 release

- roles/linux/opensearch/templates/jvm.options
Add new jvm.options for Java 21, as required by OpenSearch 3.0
resolves missing jvm.options
> update jvm.options for java21
