opensearch-project/ansible-playbook

- inventories/opensearch/group_vars/all/all.yml
> Bump version OpenSearch/Dashboards 1.1.0

- inventories/opensearch/group_vars/all/all.yml
> bump version to 1.2.0

- inventories/opensearch/group_vars/all/all.yml
- roles/centos7/dashboards/tasks/dashboards.yml
> separate dashboards version

- inventories/opensearch/group_vars/all/all.yml
> Update to 1.2.2

- inventories/opensearch/group_vars/all/all.yml
Update opensearch and dashboards to use 1.3.0 version
https://opensearch.org/blog/releases/2022/03/launch-announcement-1-3-0/
> Update opensearch and dashboards to use 1.3.0 version

- MAINTAINERS.md
- README.md
- inventories/opensearch/group_vars/all/all.yml
Update ansible to run with opensearch 1.3.1
> Update ansible to run with opensearch 1.3.1

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Abhinav Gupta <abhng@amazon.com>
Update the opensearch-dashboards for 1.3.1 release
https://github.com/opensearch-project/opensearch-build/issues/1885
> update opensearch-dashboards with 1.3.1

- MAINTAINERS.md
Add Saravanan30erd as the new community maintainer
> Add Saravanan30erd as the new community maintainer

- inventories/opensearch/group_vars/all/all.yml
Add optional 2.x version OpenSearch for the playbook
> Add optional 2.x version OpenSearch for the playbook

- inventories/opensearch/group_vars/all/all.yml
Update 1.3.2 version for the ansible playbook
https://github.com/opensearch-project/opensearch-build/issues/1882
> Update 1.3.2 version for the ansible playbook

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Update 2.0.1 version for ansible playbook
Part of https://github.com/opensearch-project/opensearch-build/issues/2165
> Update 2.0.1 version for ansible playbook

- .github/CODEOWNERS
Add saravanan30erd as the default reviewer of ansible repo
> Add saravanan30erd as the default reviewer of ansible repo

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: pgodithi <pgodithi@amazon.com>
Release 2.1.0.
https://github.com/opensearch-project/opensearch-build/issues/1818
> Release 2.1.0

- README.md
- files/internal_users.yml
- files/roles.yml
- files/roles_mapping.yml
- files/tenants.yml
- inventories/opensearch/group_vars/all/all.yml
- roles/linux/dashboards/defaults/main.yml
- roles/linux/dashboards/tasks/dashboards.yml
- roles/linux/dashboards/templates/opensearch_dashboards.yml
- roles/linux/opensearch/defaults/main.yml
- roles/linux/opensearch/tasks/opensearch.yml
- roles/linux/opensearch/tasks/security.yml
- roles/linux/opensearch/templates/security_plugin_conf.yml
- roles/linux/opensearch/templates/tlsconfig.yml
[Backport 1.x] OIDC auth, custom configs #63 
> [Backport 1.x] OIDC auth, custom configs

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Update to 1.3.4 version
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
> Update to 1.3.4 version

- inventories/opensearch/group_vars/all/all.yml
Update app version to user 2.2.0 artifacts
> Update app version to user 2.2.0 artifacts

- inventories/opensearch/group_vars/all/all.yml
[Release 1.3.5] Update version to 1.3.5
Part of https://github.com/opensearch-project/opensearch-build/issues/2348
> [Release 1.3.5] Update version to 1.3.5

- inventories/opensearch/group_vars/all/all.yml
[Release 2.2.1] Update version to 2.2.1. 
Part of https://github.com/opensearch-project/opensearch-build/issues/2481
> [Release 2.2.1] Update version to 2.2.1. 

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Since 2.3.0 is out, bumping the version to consume it. 
> Update versions to 2.3.0

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 1.3.6
Part of https://github.com/opensearch-project/opensearch-build/issues/2650
> Update version to 1.3.6 post release

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Update versions for 2.4.0 release
Part of post release activity for https://github.com/opensearch-project/opensearch-build/issues/2649
> Update versions for 2.4.0 release

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Update version to 1.3.7
https://github.com/opensearch-project/opensearch-build/issues/2742
> Update version to 1.3.7

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Update version to 2.4.1
> Update version to 2.4.1

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Bump version to 2.5.0. 
> Bump version to 2.5.0

- inventories/opensearch/group_vars/all/all.yml
Signed-off-by: Rishabh Singh <sngri@amazon.com>
version bump to 1.3.8. 
> version bump to 1.3.8

- inventories/opensearch/group_vars/all/all.yml
Bump OpenSearch and Dashboards to 2.6.0
> Bump OpenSearch and Dashboards to 2.6.0

- .github/CODEOWNERS
- MAINTAINERS.md
Updating the CODEOWNERS and MAINTAINERS file
Closes #114 
> Updating the CODEOWNERS and MAINTAINERS file

- roles/linux/opensearch/tasks/main.yml
use ansible.builtin.uri instead of curl
#124 
> Fixes #124: Replace curl by uri

- opensearch.yml
- roles/linux/dashboards/handlers/main.yml
- roles/linux/dashboards/tasks/dashboards.yml
- roles/linux/dashboards/tasks/etchosts.yml
- roles/linux/dashboards/tasks/main.yml
- roles/linux/dashboards/tasks/tune.yml
- roles/linux/opensearch/handlers/main.yml
- roles/linux/opensearch/tasks/etchosts.yml
- roles/linux/opensearch/tasks/main.yml
- roles/linux/opensearch/tasks/opensearch.yml
- roles/linux/opensearch/tasks/security.yml
- roles/linux/opensearch/tasks/tune.yml
Fixes a couple of ansible-lint errors
Cosmetic changes
> Fix a couple of ansible-lint errors

- inventories/opensearch/group_vars/all/all.yml
Increment version to 2.7.0
Part of https://github.com/opensearch-project/opensearch-build/issues/3230
> Increment OS & OSD version to 2.7.0

- inventories/opensearch/group_vars/all/all.yml
Release version 1.3.10
https://github.com/opensearch-project/opensearch-build/issues/3331
> Release version 1.3.10

- inventories/opensearch/group_vars/all/all.yml
Increment OS & OSD version to 2.8.0. 
> Increment OS & OSD version to 2.8.0

- inventories/opensearch/group_vars/all/all.yml
[Release 2.9.0] Playbook upgrade
Part of https://github.com/opensearch-project/opensearch-build/issues/3616
> [Release 2.9.0] Playbook upgrade

- roles/linux/opensearch/tasks/security.yml
> Duplicate of previous task

- .github/CODEOWNERS
- MAINTAINERS.md
- README.md
- opensearch.yml
- roles/linux/dashboards/handlers/main.yml
- roles/linux/dashboards/tasks/dashboards.yml
- roles/linux/dashboards/tasks/etchosts.yml
- roles/linux/dashboards/tasks/main.yml
- roles/linux/dashboards/tasks/tune.yml
- roles/linux/opensearch/handlers/main.yml
- roles/linux/opensearch/tasks/etchosts.yml
- roles/linux/opensearch/tasks/main.yml
- roles/linux/opensearch/tasks/opensearch.yml
- roles/linux/opensearch/tasks/security.yml
- roles/linux/opensearch/tasks/tune.yml
Backport 1.x PR #119 #129 #126 #135 #132
> Backport 1.x PR #119 #129 #126 #135 #132

- inventories/opensearch/group_vars/all/all.yml
Release version 1.3.12
https://github.com/opensearch-project/opensearch-build/issues/3709
> Release version 1.3.12

- inventories/opensearch/group_vars/all/all.yml
Increment os & osd version for the release 1.3.13
Part of https://github.com/opensearch-project/opensearch-build/issues/3878
> Increment os & osd version for the release 1.3.13

- inventories/opensearch/group_vars/all/all.yml
Increment OpenSearch and Dashboards to 2.10.0
https://github.com/opensearch-project/opensearch-build/issues/3743
> Increment OpenSearch and Dashboards to 2.10.0

- inventories/opensearch/group_vars/all/all.yml
Increment OpenSearch and Dashboards to 2.11.0. 
> Increment OpenSearch and Dashboards to 2.11.0

- inventories/opensearch/group_vars/all/all.yml
Increment OpenSearch and Dashboards to 2.11.1
https://github.com/opensearch-project/opensearch-build/issues/4161
> Increment OpenSearch and Dashboards to 2.11.1

- inventories/opensearch/group_vars/all/all.yml
Increment OS&OSD version for release 1.3.14
Part of https://github.com/opensearch-project/opensearch-build/issues/4069
> Increment OS&OSD version for release 1.3.14

- inventories/opensearch/group_vars/all/all.yml
Increment version to release 1.3.15
part of [[RELEASE] Release version 1.3.15](https://github.com/opensearch-project/opensearch-build/issues/4294)
> Increment version to release 1.3.15

- inventories/opensearch/group_vars/all/all.yml
Upgrade to OpenSearch and Dashboards 2.13.0
https://github.com/opensearch-project/opensearch-build/issues/4433
> Upgrade to OpenSearch and Dashboards 2.13.0

- inventories/opensearch/group_vars/all/all.yml
Increment version for 1.3.16 release
Part of https://github.com/opensearch-project/opensearch-build/issues/4531
> Increment version for 1.3.16 release

- inventories/opensearch/group_vars/all/all.yml
Upgrade to OpenSearch and Dashboards 2.14.0. 
https://github.com/opensearch-project/opensearch-build/issues/4562
> Upgrade to OpenSearch and Dashboards 2.14.0

- .github/CODEOWNERS
- MAINTAINERS.md
Update Maintainers.md and CODEOWNERS file
NA
> Remove @bbarani as maintainer

- inventories/opensearch/group_vars/all/all.yml
Increment version for 1.3.18 release
Part of https://github.com/opensearch-project/opensearch-build/issues/4763
> Increment version for 1.3.18 release

- roles/linux/dashboards/tasks/main.yml
- roles/linux/opensearch/tasks/main.yml
> disable selinux for debian

- roles/linux/dashboards/tasks/main.yml
- roles/linux/opensearch/tasks/main.yml
[Backport 1.x] disable selinux for debian #152 
#152
> [Backport 1.x] disable selinux for debian #152 

- inventories/opensearch/group_vars/all/all.yml
[Release 2.16.0] Update the OS and OSD version to 2.16.0
Part of https://github.com/opensearch-project/opensearch-build/issues/4771
> [Release 2.16.0] Update the OS and OSD version to 2.16.0

- inventories/opensearch/group_vars/all/all.yml
Increment version for 1.3.19
Part of https://github.com/opensearch-project/opensearch-build/issues/4888
> Increment version for 1.3.19

- inventories/opensearch/group_vars/all/all.yml
Upgrade to 2.17.0
https://github.com/opensearch-project/opensearch-build/issues/4908
> Upgrade to 2.17.0

- inventories/opensearch/group_vars/all/all.yml
> Update 2.17.1 version

- inventories/opensearch/group_vars/all/all.yml
Update version for OS-2.18.0 release. 
https://github.com/opensearch-project/opensearch-build/issues/5004. 
> Update version for OS-2.18.0 release

- inventories/opensearch/group_vars/all/all.yml
Increment version for release 1.3.20
Post https://github.com/opensearch-project/opensearch-build/issues/4990
> Increment version for release 1.3.20

- inventories/opensearch/group_vars/all/all.yml
Bump version to 2.19.0 from 2.18.0
> Increment version to 2.19.0

- inventories/opensearch/group_vars/all/all.yml
> Increment version to 2.19.1

- inventories/opensearch/group_vars/all/all.yml
Increment version to 2.19.2
Part of https://github.com/opensearch-project/opensearch-build/issues/5419
> Increment version to 2.19.2

- README.md
[Release 2.x] Switch 2.x.x to be released from 2.x branch
Resolves https://github.com/opensearch-project/ansible-playbook/issues/174
> [Release 2.x] Switch 2.x.x to be released from 2.x branch

- README.md
- inventories/opensearch/group_vars/all/all.yml
[Release 3.0] Bump main branch to 3.0.0 version
Resolves https://github.com/opensearch-project/ansible-playbook/issues/174
> [Release 3.0] Bump main branch to 3.0.0 version

- inventories/opensearch/group_vars/all/all.yml
> bump 2.x version to 2.19.3

- inventories/opensearch/group_vars/all/all.yml
Increment to 3.2
https://github.com/opensearch-project/opensearch-build/issues/5595
> Increment to 3.2
